export const FETCH_CERTIFICATIONS_START = 'FETCH_CERTIFICATIONS_START';
export const FETCH_CERTIFICATIONS_SUCCESS = 'FETCH_CERTIFICATIONS_SUCCESS';
export const FETCH_CERTIFICATIONS_FAILURE = 'FETCH_CERTIFICATIONS_FAILURE';

export const FETCH_CERTIFICATION_BY_ID = 'FETCH_CERTIFICATION_BY_ID';
export const FETCH_CERTIFICATION_BY_ID_SUCCESS = 'FETCH_CERTIFICATION_BY_ID_SUCCESS';
export const FETCH_CERTIFICATION_BY_ID__FAILURE = 'FETCH_CERTIFICATION_BY_ID_FAILURE';
