export const FETCH_CERTIFICATIONS_START = 'FETCH_CERTIFICATIONS_START';
export const FETCH_CERTIFICATIONS_SUCCESS = 'FETCH_CERTIFICATIONS_SUCCESS';
export const FETCH_CERTIFICATIONS_FAILURE = 'FETCH_CERTIFICATIONS_FAILURE';

export const ADD_CERTIFICATIONS_START = 'ADD_CERTIFICATIONS_START';
export const ADD_CERTIFICATIONS_SUCCESS = 'ADD_CERTIFICATIONS_SUCCESS';
export const ADD_CERTIFICATIONS_FAILURE = 'ADD_CERTIFICATIONS_FAILURE';

export const EDIT_CERTIFICATIONS_START = 'EDIT_CERTIFICATIONS_START';
export const EDIT_CERTIFICATIONS_SUCCESS = 'EDIT_CERTIFICATIONS_SUCCESS';
export const EDIT_CERTIFICATIONS_FAILURE = 'EDIT_CERTIFICATIONS_FAILURE';

export const FETCH_CERTIFICATION_BY_ID_START = 'FETCH_CERTIFICATION_BY_ID_START';
export const FETCH_CERTIFICATION_BY_ID_SUCCESS = 'FETCH_CERTIFICATION_BY_ID_SUCCESS';
export const FETCH_CERTIFICATION_BY_ID__FAILURE = 'FETCH_CERTIFICATION_BY_ID_FAILURE';
