export const FETCH_QUESTIONS_BY_IDS_START = 'FETCH_QUESTIONS_BY_IDS_START'
export const FETCH_QUESTIONS_BY_IDS_SUCCESS = 'FETCH_QUESTIONS_BY_IDS_SUCCESS'
export const FETCH_QUESTIONS_BY_IDS_FAILURE = 'FETCH_QUESTIONS_BY_IDS_FAILURE'

export const ADD_QUESTION_START = 'ADD_QUESTION_START'
export const ADD_QUESTION_SUCCESS = 'ADD_QUESTION_SUCCESS'
export const ADD_QUESTION_FAILURE = 'ADD_QUESTION_FAILURE'

export const UPDATE_QUESTION_START = 'UPDATE_QUESTION_START'
export const UPDATE_QUESTION_SUCCESS = 'UPDATE_QUESTION_SUCCESS'
export const UPDATE_QUESTION_FAILURE = 'UPDATE_QUESTION_FAILURE'

export const FETCH_QUESTION_BY_ID_START = 'FETCH_QUESTION_BY_ID_START'
export const FETCH_QUESTION_BY_ID_SUCCESS = 'FETCH_QUESTION_BY_ID_SUCCESS'
export const FETCH_QUESTION_BY_ID_FAILURE = 'FETCH_QUESTION_BY_ID_FAILURE'
